# Generated by Django 5.1.1 on 2024-10-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_client_merchant_delete_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='ClientProfile',
        ),
        migrations.RenameModel(
            old_name='Merchant',
            new_name='MerchantProfile',
        ),
    ]
